Add optional hook-in script, fix collision comparison, implement custom ignore list via hook, replace both ls-tree reads with a filter function, and replace SUBMODULE_PATH with SUBMOD_PATH

diff --git a/bin/dotfiles-submodule-symlinks b/bin/dotfiles-submodule-symlinks
--- a/bin/dotfiles-submodule-symlinks
+++ b/bin/dotfiles-submodule-symlinks
@@ -18,9 +18,23 @@ esac
 "  
 }
 
+# DSS_HOOKIN_SOURCE defaults to .include/dotfiles-submodule-symlinks-hook.sh
+#     This is the PATH to a hook-in script that will be sourced if it exists.
+#     It provides a way to optionally source a script that can be used to add
+#     customisation in any of the provided ways, or any other way, if you know
+#     what you're doing. """Intended""" options are listed here;
+DSS_HOOKIN_SOURCE_DEFAULT=".include/dotfiles-submodule-symlinks-hook.sh"
+: "${DSS_HOOKIN_SOURCE:=$DSS_HOOKIN_SOURCE_DEFAULT}"
+# CLOBBER_CHECKEDIN_ROOT_IGNORELIST can be set as an array in the hook script,
+#     and will be added to the GLOBALLY_IGNORED_FILES to bypass these from the
+#     tracked collision test, so CLOBBER_CHECKEDIN_ROOT can be set to "ERROR",
+#     except for explicitely approved clobbering files in this list. This is
+#     where you would list for example gpg config files, as they are core to
+#     this basic dotfiles setup, but are not themselves extendible / includable.
+
 # CLOBBER_CHECKEDIN_ROOT defaults to ERROR
 #     ERROR means that if a file is checked in in both the root module and this
-#     as a submodule, besides files this ignores above, then fail this process.
+#     as a submodule, besides files this ignores below, then fail this process.
 #     WARN means that instead of erroring, a warning is printed, and that link
 #     is not written (the file in the root module won't be symlinked over, but
 #     the script will continue to overwrite other non-checked-in files).
@@ -50,17 +64,19 @@ VALIDATE_INPUT "CLOBBER_HOME" "ONLYLINKS|NODIFF|DESTRUCTIVE|GRACEFULLY"
 : "${EXECUTION_CONTEXT:=HOME}"
 VALIDATE_INPUT "EXECUTION_CONTEXT" "HOME|TEST"
 
-# SUBMODULE_PATH defaults to dotfiles
+# SUBMOD_PATH defaults to dotfiles
 #     This is the value of the PATH that this is submoduled under.
-: "${SUBMODULE_PATH:=dotfiles}"
+: "${SUBMOD_PATH:=dotfiles}"
 
 # If EXECUTION_CONTEXT=TEST then set the "PWD Test" and "DOTFILES" paths.
 REPO_ROOT=$(git rev-parse --show-toplevel 2>/dev/null || pwd)
 _PWD="$(pwd)" # ~= "~"
-_SUBMOD="$_PWD/$SUBMODULE_PATH" # ~= "~/dotfiles"
+_SUBMOD="$_PWD/$SUBMOD_PATH" # ~= "~/dotfiles"
+_HOOK_SOURCE="$_PWD/$DSS_HOOKIN_SOURCE"
 
 echo
-echo "SUBMODULE PATH IS SET TO $SUBMODULE_PATH"
+echo "SUBMODULE PATH IS SET TO $SUBMOD_PATH"
+echo "HOOK-IN PATH IS SET TO $DSS_HOOKIN_SOURCE"
 if [ "$EXECUTION_CONTEXT" == "HOME" ]; then
   if [ "$(pwd)" == "$HOME" ]; then
     echo "EXECUTION_CONTEXT is HOME running in $HOME"
@@ -70,13 +86,15 @@ if [ "$EXECUTION_CONTEXT" == "HOME" ]; then
     echo "  Rerun this with"
     # Check each input against its default, see if it should be added to rerun
     RERUN_ARGS="EXECUTION_CONTEXT=TEST"
-    [ "$SUBMODULE_PATH" != "dotfiles" ] && \
-    RERUN_ARGS="$RERUN_ARGS SUBMODULE_PATH=$SUBMODULE_PATH"
+    [ "$DSS_HOOKIN_SOURCE" != "$DSS_HOOKIN_SOURCE_DEFAULT" ] && \
+    RERUN_ARGS="$RERUN_ARGS DSS_HOOKIN_SOURCE=$DSS_HOOKIN_SOURCE"
+    [ "$SUBMOD_PATH" != "dotfiles" ] && \
+    RERUN_ARGS="$RERUN_ARGS SUBMOD_PATH=$SUBMOD_PATH"
     [ "$CLOBBER_CHECKEDIN_ROOT" != "ERROR" ] && \
     RERUN_ARGS="$RERUN_ARGS CLOBBER_CHECKEDIN_ROOT=$CLOBBER_CHECKEDIN_ROOT"
     [ "$CLOBBER_HOME" != "ONLYLINKS" ] && \
     RERUN_ARGS="$RERUN_ARGS CLOBBER_HOME=$CLOBBER_HOME"
-    echo "  $RERUN_ARGS ./$SUBMODULE_PATH/bin/dotfiles-submodule-symlinks"
+    echo "  $RERUN_ARGS ./$SUBMOD_PATH/bin/dotfiles-submodule-symlinks"
     exit 127
   fi
 else
@@ -91,10 +109,23 @@ else
   fi
 fi
 
+# Here is where we source the optional hookin script set in DSS_HOOKIN_SOURCE.
+_HOOK_RAN=0
+if [[ -f "$_HOOK_SOURCE" ]]; then
+  _HOOK_RAN=1
+  source "$_HOOK_SOURCE"
+else
+  echo "Optional hook-in script '$_HOOK_SOURCE' does not exist, skipping."
+  if [[ "$DSS_HOOKIN_SOURCE" != "$DSS_HOOKIN_SOURCE_DEFAULT" ]]; then
+    echo "Optional hook-in script was non-default yet didn't exist. Exiting."
+    exit 127
+  fi
+fi
+
 # Ignored files ~ files that can't be symlinks that this will ignore.
 # Each is the full path internal to either the root or submodule, sans ~/ prefix
 GLOBALLY_IGNORED_FILES=(
-"$SUBMODULE_PATH" # ~= "dotfiles"
+"$SUBMOD_PATH" # ~= "dotfiles"
 # "dotfiles" itself must be ignored as git will track the submodule as a file.
 # Likewise the submodule contains a ".git" file that stores the hash, but git
 # doesn't consider this "tracked", and `git ls-tree` is how we're capturing what
@@ -103,35 +134,39 @@ GLOBALLY_IGNORED_FILES=(
 ".gitattributes"
 ".gitmodules"
 )
+IGNORED_FILES=(
+"${GLOBALLY_IGNORED_FILES[@]}"
+"${CLOBBER_CHECKEDIN_ROOT_IGNORELIST[@]}"
+)
 
 # List files tracked in the repo root, and by this repo as a submodule.
 # Use ~ $(git -C "<directory>" ls-tree --full-tree --name-only -r HEAD)
 # But read it with readarray to handle entries with spaces.
+filter_array() {
+  local -n arr=$1
+  local -n ignore_list=$2
+  local -n ret=$3
+  local -a filtered=()
+  for item in "${arr[@]}"; do
+    skip=
+    for ignore in "${ignore_list[@]}"; do
+      [[ "$item" == "$ignore" ]] && skip=1
+    done
+    [[ -z "$skip" ]] && filtered+=("$item")
+  done
+  ret=("${filtered[@]}")
+}
 readarray -t _LS < <(git -C "$_PWD" ls-tree --full-tree --name-only -r HEAD)
-ROOT_TRACKED=()
-for item in "${_LS[@]}"; do
-  skip=
-  for ignore in "${GLOBALLY_IGNORED_FILES[@]}"; do
-    [[ "$item" == "$ignore" ]] && skip=1
-  done
-  [[ -z "$skip" ]] && ROOT_TRACKED+=("$item")
-done
+filter_array _LS IGNORED_FILES ROOT_TRACKED
 readarray -t _LS < <(git -C "$_SUBMOD" ls-tree --full-tree --name-only -r HEAD)
-SUBMODULE_TRACKED=()
-for item in "${_LS[@]}"; do
-  skip=
-  for ignore in "${GLOBALLY_IGNORED_FILES[@]}"; do
-    [[ "$item" == "$ignore" ]] && skip=1
-  done
-  [[ -z "$skip" ]] && SUBMODULE_TRACKED+=("$item")
-done
+filter_array _LS IGNORED_FILES SUBMODULE_TRACKED
 # Iterate both lists to get a list of all collisions and non-collisions.
 TRACKED_FILES_COLLIDING=()
 TRACKED_FILES_NONCOLLIDING=()
 for subpath in "${SUBMODULE_TRACKED[@]}"; do
   _collided=0
   for rootpath in "${ROOT_TRACKED[@]}"; do
-    if [ "$rootpath" == " $subpath " ] ; then
+    if [ "$rootpath" == "$subpath" ] ; then
       TRACKED_FILES_COLLIDING+=("$subpath")
       _collided=1
     fi
@@ -144,11 +179,17 @@ done
 # Write out the discovered tracked files
 echo
 echo CLOBBER_CHECKEDIN_ROOT is set to $CLOBBER_CHECKEDIN_ROOT;
-echo "  GLOBALLY_IGNORED_FILES ARE --"
+echo "  GLOBALLY_IGNORED_FILES ARE -- (ignored by this)"
 printf '    %s\n' "${GLOBALLY_IGNORED_FILES[@]}"
-echo "  ROOT TRACKED FILES ignoring globally ignored list"
+if [ "$_HOOK_RAN" == "1" ] ; then
+  echo "  CLOBBER_CHECKEDIN_ROOT_IGNORELIST IS -- (ignored by this)"
+  printf '    %s\n' "${CLOBBER_CHECKEDIN_ROOT_IGNORELIST[@]}"
+else
+  echo "  CLOBBER_CHECKEDIN_ROOT_IGNORELIST IS -- (no hook ran)"
+fi
+echo "  ROOT TRACKED FILES -- ignoring the ignored list(s)"
 printf '    %s\n' "${ROOT_TRACKED[@]}"
-echo "  SUBMODULE TRACKED FILES"
+echo "  SUBMODULE TRACKED FILES -- ignoring the ignored list(s)"
 printf '    %s\n' "${SUBMODULE_TRACKED[@]}"
 
 # Write out the status of collisions and non-collisions.
@@ -168,9 +209,9 @@ else
     'REPLACE')
       echo "  COLLISIONS FOUND, REPLACE -- REPLACING ROOT'S COPY WITH THIS'S";
       for collider in "${TRACKED_FILES_COLLIDING[@]}"; do
-        echo " Copying $SUBMODULE_PATH/$collider over $collider"
+        echo " Copying $SUBMOD_PATH/$collider over $collider"
         rm "$collider"
-        cp "$SUBMODULE_PATH/$collider" "$collider"
+        cp "$SUBMOD_PATH/$collider" "$collider"
       done ;;
     *)
       exit 127;;
@@ -188,7 +229,7 @@ action-onlylinks() {
   else
     if [ "$IS_SYMLINK_ALREADY" == "true" ] ; then
       if [ "$SYMLINK_ALREADY_LINKS_TO_TARGET" == "true" ] ; then
-        echo "    $tracked_file already linked $SUBMODULE_PATH/$tracked_file"
+        echo "    $tracked_file already linked $SUBMOD_PATH/$tracked_file"
       else
         echo "    Replacing exisitng link $tracked_file"
         rm "$tracked_file"
@@ -204,7 +245,7 @@ action-nodiff() {
   # action-onlylinks done before this, so we only need file exists not symlink
   if [ "$FILE_ALREADY_EXISTS" == "true" ] ; then
     if [ "$IS_SYMLINK_ALREADY" == "false" ] ; then
-      if [ "$(diff "$tracked_file" "$SUBMODULE_PATH/$tracked_file")" == "" ] ; then
+      if [ "$(diff "$tracked_file" "$SUBMOD_PATH/$tracked_file")" == "" ] ; then
         # Empty diff
         echo "    File $tracked_file has an empty diff, replace with symlink"
         rm "$tracked_file"
@@ -220,7 +261,7 @@ action-nodiff() {
 action-gracefully() {
   if [ "$FILE_ALREADY_EXISTS" == "true" ] ; then
     if [ "$IS_SYMLINK_ALREADY" == "false" ] ; then
-      if [ "$(diff "$tracked_file" "$SUBMODULE_PATH/$tracked_file")" != "" ] ; then
+      if [ "$(diff "$tracked_file" "$SUBMOD_PATH/$tracked_file")" != "" ] ; then
         # Exists, not a symlink, Non-empty diff :: backup and symlink
         mkdir -p "$_PWD/.include/.clobbered/$(dirname "$tracked_file")"
         mv "$tracked_file" "$_PWD/.include/.clobbered/$tracked_file"
